var annotated =
[
    [ "AsymmetricQuantizationError", "structAsymmetricQuantizationError.html", null ],
    [ "CombinedError", "structCombinedError.html", "structCombinedError" ],
    [ "DepthColorArraySizeMismatch", "structDepthColorArraySizeMismatch.html", "structDepthColorArraySizeMismatch" ],
    [ "DepthModel", "classDepthModel.html", "classDepthModel" ],
    [ "InvalidFloat32QuantizationTypeError", "structInvalidFloat32QuantizationTypeError.html", "structInvalidFloat32QuantizationTypeError" ],
    [ "InvalidQuantizedType", "structInvalidQuantizedType.html", "structInvalidQuantizedType" ],
    [ "MinMaxOperator", "classMinMaxOperator.html", "classMinMaxOperator" ],
    [ "MutexGuard", "classMutexGuard.html", "classMutexGuard" ],
    [ "Operator", "classOperator.html", "classOperator" ],
    [ "OperatorError", "structOperatorError.html", "structOperatorError" ],
    [ "Overloads", "structOverloads.html", null ],
    [ "ProfileScope", "structProfileScope.html", "structProfileScope" ],
    [ "ProfileScopeRecord", "structProfileScopeRecord.html", "structProfileScopeRecord" ],
    [ "ProfilingFrame", "classProfilingFrame.html", "classProfilingFrame" ],
    [ "QuantizationElementsMismatch", "structQuantizationElementsMismatch.html", "structQuantizationElementsMismatch" ],
    [ "RgbNormalizeOperator", "classRgbNormalizeOperator.html", "classRgbNormalizeOperator" ],
    [ "RgbNormalizeOperatorYolo", "classRgbNormalizeOperatorYolo.html", "classRgbNormalizeOperatorYolo" ],
    [ "TensorType", "classTensorType.html", "classTensorType" ],
    [ "TfLiteAllocateTensorsError", "structTfLiteAllocateTensorsError.html", "structTfLiteAllocateTensorsError" ],
    [ "TfLiteCopyFromInputTensorError", "structTfLiteCopyFromInputTensorError.html", "structTfLiteCopyFromInputTensorError" ],
    [ "TfLiteCopyToOutputTensorError", "structTfLiteCopyToOutputTensorError.html", "structTfLiteCopyToOutputTensorError" ],
    [ "TfLiteCreateInterpreterError", "structTfLiteCreateInterpreterError.html", null ],
    [ "TfLiteInvokeInterpreterError", "structTfLiteInvokeInterpreterError.html", "structTfLiteInvokeInterpreterError" ],
    [ "TfLiteNonFloatTensorTypeError", "structTfLiteNonFloatTensorTypeError.html", "structTfLiteNonFloatTensorTypeError" ],
    [ "TfLiteReporterUserData", "structTfLiteReporterUserData.html", "structTfLiteReporterUserData" ],
    [ "TfLiteRuntime", "classTfLiteRuntime.html", "classTfLiteRuntime" ],
    [ "TfLiteRuntimeBuilder", "classTfLiteRuntimeBuilder.html", "classTfLiteRuntimeBuilder" ],
    [ "TfLiteTensorElementCountMismatch", "structTfLiteTensorElementCountMismatch.html", "structTfLiteTensorElementCountMismatch" ],
    [ "TfLiteTensorsNotCreatedError", "structTfLiteTensorsNotCreatedError.html", "structTfLiteTensorsNotCreatedError" ],
    [ "YoloModel", "classYoloModel.html", "classYoloModel" ]
];